### ISSUE TITLE
mdx plugins are not allowed?

### ISSUE THREAD

**Issue by mununki** [IanChen83/next-mdx-frontmatter#1]
Hi, I've been looking for the module to parse the frontmatter with having dependencies on mdx and next. So, I'm very glad to find your work.

Actually, I've implemented `@zeit/next-mdx` to my project, and it works like charm especially with plugins such as `remark-images`, `remark-emoji`, `remark-highlight`. But I implemented your module to my project like below code, the frontmatter seems parsed and not showing after rendered, it's good!  but I found that the plugins are not working at all. Specially, my codes in *.md are parsed, but `highlight` plugins are not working for my codes.

Can you advise me of any solution?

// next.config.js
```js
const images = require("remark-images")
const emoji = require("remark-emoji")
const highlight = require("remark-highlight.js")
const exportPathMap = require("./export.config")

// I changed only this code from `@zeit/next-mdx` to `next-mdx-frontmatter`
const withMDX = require("next-mdx-frontmatter")({
  extension: /\.(md|mdx)?$/,
  options: {
    mdPlugins: [images, emoji, highlight]
  }
})

module.exports = withMDX({
  exportPathMap: () => {
    return exportPathMap
  }
})
```

**Comment by mununki** [comment]
I found a solution after looked into your [source code](https://github.com/IanChen83/next-mdx-frontmatter/blob/1bdb5df32b0236cc0dc6b858d4b7cc964d310947/index.js#L4)

I've changed my `next.config.js` as below, I checked the plugins are working as I intended.

// next.config.js
```js
const withMDX = require("next-mdx-frontmatter")({
  extension: /\.(md|mdx)?$/,
// your source code reads `MDXOptions` as option object
  MDXOptions: {
    mdPlugins: [images, emoji, highlight]
  }
});

module.exports = withMDX({
  exportPathMap: () => {
    return exportPathMap;
  }
});
```

Therefore, your README.md needs to be amended, current README.md says `MDXoption`, but correction is `MDXOptions`.

**Comment by IanChen83** [comment]
Oh!!! Thank you for your help and the PR! Or the inconsistency will be there forever...
